task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 3 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ../QuadTrack/train
    ann_file: ../QuadTrack/train_coco_depth.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
    window_len: 4
    window_interval: 2
  shuffle: False
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ../QuadTrack/test
    ann_file: ../QuadTrack/test_coco_depth.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
    window_len: 1
    window_interval: 1
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: EvalBatchImageCollateFunction